### ISSUE TITLE
Syscalls don't modify errno (incorrect use of last_os_error).

### ISSUE THREAD

**Issue by eddyb** [jimblandy/perf-event#3]
`perf_event_open` uses `io::Error::last_os_error()`
(which is roughly `io::Error::from_raw_os_error(libc::errno)`):
https://github.com/jimblandy/perf-event/blob/6e6618fcc6f8d53b679c91e18cd35cd5cdfefc8a/src/syscalls.rs#L22-L24

However, because this is a syscall, the error is encoded in `result` so `io::Error::from_raw_os_error(-result)` should be used instead.

**Comment by eddyb** [comment]
Actually, looks like the file that's in, `syscalls.rs` isn't even used anywhere.

However, the bug still exists in `check_syscall` (but only when used with `perf_event_open`): https://github.com/jimblandy/perf-event/blob/6e6618fcc6f8d53b679c91e18cd35cd5cdfefc8a/src/lib.rs#L784-L794

**Comment by jimblandy** [comment]
> Actually, looks like the file that's in, `syscalls.rs` isn't even used anywhere.

Oh, that code got moved to the `perf-event-open-sys` crate, so yes, that file should be deleted. The attempt to handle errors was removed in the process of moving it.

It seems like `check_syscall` is applied to a mix of things that set and do not set `errno`. That'll need some working out.

**Comment by jimblandy** [comment]
Fix published as perf-event 0.4.3.
